AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  studentcheckout-s3sns

  Sample SAM Template for studentcheckout-s3sns

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    CodeUri: studentcheckout
    Runtime: java11
    MemorySize: 512
    Timeout: 20

Resources:
  StudentCheckoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}

  StudentCheckoutTopic:
    Type: AWS::SNS::Topic

  GradeCalculatorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: ca.josue.aws.lambda.GradeCalculator::handler
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName : !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt StudentCheckoutTopic.TopicName
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          STUDENT_CHECKOUT_TOPIC: !Ref StudentCheckoutTopic
      Events:
        S3Event:
          Type: S3 # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Bucket: !Ref StudentCheckoutBucket
            Events: s3:ObjectCreated:*

  ReportGeneratorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: ca.josue.aws.lambda.ReportGenerator::handler
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: SNS # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Topic: !Ref StudentCheckoutTopic